<#
.SYNOPSIS
    Runs the Linksi URL cleaner / URL normalizer unit tests without the Android SDK.

.DESCRIPTION
    The Android Gradle module cannot be configured without an Android SDK, so `gradlew :app:test`
    is unavailable on machines that only need the URL logic. The URL cleaner and URL normalizer
    are deliberately free of `android.*` imports and are therefore pure Kotlin/JVM code.

    This script generates a throwaway Gradle JVM project next to the repository, copies the
    *verbatim* source and test files from the Android project into it and runs the *verbatim*
    unit tests on a real JVM. Nothing is re-implemented or translated: the same .kt files that
    ship in the app are the ones under test.

    The tests are always forced to re-execute (cleanTest) and the JUnit XML is parsed afterwards,
    so a "BUILD SUCCESSFUL" that skipped the tests cannot be mistaken for a passing run. The
    script exits non-zero if any test fails, if an error occurs, or if no test ran at all.

.EXAMPLE
    powershell -File .\tools\run-urlcleaner-tests.ps1

.EXAMPLE
    powershell -File .\tools\run-urlcleaner-tests.ps1 -JavaHome 'C:\Program Files\Java\jdk-17'
#>
[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string]$VerifyDir,
    [string]$JavaHome,
    [string]$GradleUserHome
)

$ErrorActionPreference = 'Stop'

if (-not $RepoRoot) { $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path }
$RepoRoot = (Resolve-Path $RepoRoot).Path
$parent = Split-Path $RepoRoot -Parent

# The project keeps its toolchain and caches beside the repository, under the Linksi umbrella folder.
$local = Join-Path $parent 'local'

if (-not $VerifyDir)      { $VerifyDir      = Join-Path $parent 'linksi-urlcleaner-verify' }
if (-not $GradleUserHome) { $GradleUserHome = Join-Path $local '.gradle-verify-home' }
if (-not $JavaHome) {
    $candidates = @(
        (Join-Path $parent 'toolchain\jdk-17'),
        $env:JAVA_HOME,
        # The JetBrains Runtime bundled with the JetBrains IDEs is also a full JDK.
        'C:\Program Files\JetBrains\PyCharm Community Edition 2024.2.4\jbr'
    )
    $JavaHome = $candidates |
        Where-Object { $_ -and (Test-Path (Join-Path $_ 'bin\java.exe')) } |
        Select-Object -First 1
}
if (-not $JavaHome -or -not (Test-Path (Join-Path $JavaHome 'bin\java.exe'))) {
    throw "No JDK found. Install a JDK 17+ and pass -JavaHome <path>."
}

$tmpDir = Join-Path $local '.tmp'
New-Item -ItemType Directory -Force -Path $VerifyDir, $GradleUserHome, $tmpDir | Out-Null

# ── the throwaway JVM project ─────────────────────────────────────────────────
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$settingsKts = @'
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = "linksi-urlcleaner-verify"
'@

$buildKts = @'
// Generated by tools/run-urlcleaner-tests.ps1 - do not edit by hand.
plugins {
    kotlin("jvm") version "2.0.21"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("junit:junit:4.13.2")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
}
'@

[System.IO.File]::WriteAllText((Join-Path $VerifyDir 'settings.gradle.kts'), $settingsKts, $utf8NoBom)
[System.IO.File]::WriteAllText((Join-Path $VerifyDir 'build.gradle.kts'), $buildKts, $utf8NoBom)

# ── copy the real sources and tests verbatim ──────────────────────────────────
$pairs = @(
    @{ From = "$RepoRoot\app\src\main\java\com\linksi\app\utils\UrlCleaner.kt";        To = "$VerifyDir\src\main\kotlin\com\linksi\app\utils\UrlCleaner.kt" },
    @{ From = "$RepoRoot\app\src\main\java\com\linksi\app\utils\UrlNormalizer.kt";     To = "$VerifyDir\src\main\kotlin\com\linksi\app\utils\UrlNormalizer.kt" },
    @{ From = "$RepoRoot\app\src\test\java\com\linksi\app\utils\UrlCleanerTest.kt";    To = "$VerifyDir\src\test\kotlin\com\linksi\app\utils\UrlCleanerTest.kt" },
    @{ From = "$RepoRoot\app\src\test\java\com\linksi\app\utils\UrlNormalizerTest.kt"; To = "$VerifyDir\src\test\kotlin\com\linksi\app\utils\UrlNormalizerTest.kt" }
)

foreach ($pair in $pairs) {
    if (-not (Test-Path $pair.From)) { throw "missing source file: $($pair.From)" }
    $dir = Split-Path $pair.To -Parent
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    Copy-Item $pair.From $pair.To -Force
    Write-Host "synced $(Split-Path $pair.From -Leaf)"
}

# ── run the tests ─────────────────────────────────────────────────────────────
$env:JAVA_HOME = $JavaHome
$env:GRADLE_USER_HOME = $GradleUserHome
$env:GRADLE_OPTS = "-Djava.io.tmpdir=$tmpDir"

# Gradle writes progress to stderr; with 'Stop' plus 2>&1 PowerShell would turn that into a
# terminating error and abort before the exit code can be read.
$ErrorActionPreference = 'Continue'

# --no-watch-fs avoids the native file watcher, which some sandboxes deny.
# cleanTest forces the tests to actually execute instead of being reported UP-TO-DATE.
$log = Join-Path $VerifyDir 'test-run.log'
& "$RepoRoot\gradlew.bat" -p $VerifyDir cleanTest test --console=plain --no-watch-fs 2>&1 |
    Tee-Object -FilePath $log
$code = $LASTEXITCODE

# ── verify from the JUnit XML, not from Gradle's console output ───────────────
$resultsDir = Join-Path $VerifyDir 'build\test-results\test'
$tot = 0; $fail = 0; $err = 0
Get-ChildItem $resultsDir -Filter *.xml -ErrorAction SilentlyContinue | ForEach-Object {
    [xml]$x = Get-Content $_.FullName
    $s = $x.testsuite
    Write-Host ("  {0}: tests={1} failures={2} errors={3} skipped={4}" -f $s.name, $s.tests, $s.failures, $s.errors, $s.skipped)
    $tot += [int]$s.tests; $fail += [int]$s.failures; $err += [int]$s.errors
}

Write-Host ""
Write-Host ("=== gradle exit code: {0} ; junit tests={1} failures={2} errors={3} ===" -f $code, $tot, $fail, $err)
Write-Host "=== full log: $log ==="

if ($tot -eq 0) { Write-Host 'NO TESTS RAN - treating as failure'; exit 1 }
if ($fail -gt 0 -or $err -gt 0) { exit 1 }
exit $code
